// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNuBkE6j7VFmPqc5ixGJpxVyhaKKx9axI',
    appId: '1:1088680595775:web:699760613df889ff5fc38a',
    messagingSenderId: '1088680595775',
    projectId: 'horas-v3-9c40f',
    authDomain: 'horas-v3-9c40f.firebaseapp.com',
    storageBucket: 'horas-v3-9c40f.firebasestorage.app',
    measurementId: 'G-Q2WRLE8V6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLAnLJWTqaXFljiotLyXBAfTVGX1sQUxY',
    appId: '1:1088680595775:android:c3fcb3694abb91d75fc38a',
    messagingSenderId: '1088680595775',
    projectId: 'horas-v3-9c40f',
    storageBucket: 'horas-v3-9c40f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV_Uj4QIukCXbzMEVB1G-6iKFhsN5d_dE',
    appId: '1:1088680595775:ios:fec4ca3d63d6c5b45fc38a',
    messagingSenderId: '1088680595775',
    projectId: 'horas-v3-9c40f',
    storageBucket: 'horas-v3-9c40f.firebasestorage.app',
    iosBundleId: 'com.example.projectOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV_Uj4QIukCXbzMEVB1G-6iKFhsN5d_dE',
    appId: '1:1088680595775:ios:fec4ca3d63d6c5b45fc38a',
    messagingSenderId: '1088680595775',
    projectId: 'horas-v3-9c40f',
    storageBucket: 'horas-v3-9c40f.firebasestorage.app',
    iosBundleId: 'com.example.projectOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNuBkE6j7VFmPqc5ixGJpxVyhaKKx9axI',
    appId: '1:1088680595775:web:d2116e27004e0d745fc38a',
    messagingSenderId: '1088680595775',
    projectId: 'horas-v3-9c40f',
    authDomain: 'horas-v3-9c40f.firebaseapp.com',
    storageBucket: 'horas-v3-9c40f.firebasestorage.app',
    measurementId: 'G-WT0TTF4SKH',
  );

}